Brief output
openflighthpc/queue-status-reporter pull request #20
Opened 2020-10-21 15:40 UTC by VoxSecundus

This PR changes the default output of the application to resemble the following codeblock. The old output has been moved, and can be retrieved by using the `verbose` command line argument. 

```
2020-10-21 16:19:38
Nodes

0 node(s) are idle
0 active node(s) have no jobs in any of their partitions

Jobs

2 total job(s) are running (0 have been running for more than 7days
2 total job(s) pending (0 total job(s) not estimated to start within 12hrs after submission)
Estimated time all jobs completed: 2020-10-21 16:58:39 +0100
```
Logically, these report items are identical to the verbose output. However, most of the superfluous data has been omitted.

2020-10-21 16:43 UTC, timalces requested changes

2020-10-21 16:43 UTC, timalces commented on queue_status.rb
> +         (": #{no_jobs_in_partitions.join(", ")}" if no_jobs_in_partitions.any?),
Perhaps we should also be highlighting any nodes that are down?

2020-10-21 16:43 UTC, timalces commented on queue_status.rb
> +         (" (#{total_long_running.length} have been running for more than #{formatted_threshold(running_threshold)}"),
Missing a closing bracket in the text here.

2020-10-21 16:43 UTC, timalces commented on queue_status.rb
> +         (" (#{total_long_waiting.length} total job(s) not estimated to start within #{formatted_threshold(wait_threshold)} after submission)"),
To be consistent with the verbose message, this should be "estimated not to start". We're also not highlighting if there any any jobs we can't estimate their start times for (if that's something we want).

2020-10-22 11:12 UTC, VoxSecundus commented
These comments have now been addressed :heavy_check_mark:

2020-10-22 11:33 UTC, timalces requested changes
Sorry, also just realised that the Readme needs updating to reflect these changes.

2020-10-22 11:33 UTC, timalces commented on queue_status.rb
> +         ("#{total_long_waiting.length} total job(s) estimated not to start within #{formatted_threshold(wait_threshold)} after submission" if !no_start_data),
The number of long waiting jobs are being displayed twice if this condition is met.

2020-10-22 11:33 UTC, timalces commented on queue_status.rb
> +         "\n"
Missing a comma at the end of this line.

2020-10-22 11:33 UTC, timalces commented on queue_status.rb
> +         ("Insufficient data to estimate job start times" if no_start_data),
This needs an` \n` at the front.

2020-10-22 11:33 UTC, timalces commented on queue_status.rb
> +         (" (#{total_long_running.length} have been running for more than #{formatted_threshold(running_threshold)})"),
Do we want to have the option to show the ids of these as well (if the ids arg given)?

2020-10-22 15:02 UTC, VoxSecundus commented
Further updates :heavy_check_mark:

2020-10-23 09:27 UTC, timalces commented on queue_status.rb
> +         "\n",
Sorry, last point! Think this `\n`should be removed now.

2020-10-23 10:53 UTC, merged